#ifndef ERROR_DEF_H_
#define ERROR_DEF_H_


enum RECORD_ERROR
{
	RECORD_ERROR_ALREADY_EXIST = 1,
	RECORD_ERROR_DONNOT_EXIST,
	RECORD_ERROR_INS_FAILURE,
	RECORD_ERROR_OPEN_VIDEO,
	RECORD_ERROR_OPEN_OUTPUT,
	RECORD_ERROR_INIT_BUFFER,
	RECORD_ERROR_CREATE_THREAD,
	RECORD_ERROR_STOP_THREAD
};

#endif
